using System;
using System.Collections.Generic;
using System.Globalization;

namespace CleanScan.ViewModels
{
    public partial class MainWindowViewModel : ViewModelBase
    {
        private static readonly Dictionary<string, Dictionary<string, string>> UiTexts = new(StringComparer.OrdinalIgnoreCase)
        {
            ["en"] = new(StringComparer.OrdinalIgnoreCase)
            {
                ["InfosMenu"] = "Infos",
                ["UserGuideMenuItem"] = "User guide",
                ["ScriptPreviewMenuItem"] = "Script preview",
                ["LanguagesMenu"] = "Languages",
                ["PresetMenuItem"] = "Preset",
                ["AboutMenuItem"] = "About",
                ["FeedbackMenuItem"] = "Feedback",
                ["SettingsMenu"] = "Settings",
                ["ThreadsLabel"] = "Threads",
                ["SourceLoaderLabel"] = "Source loader",
                ["ExpandBtnTooltip"] = "Show parameters",
                ["AllRightsReserved"] = "all rights reserved",
                ["AboutCompany"] = "ScanFilm SNC",
                ["AboutWebsite"] = "www.scanfilm.ch",
                ["AboutVersion"] = "trial version — beta 4.0",
                ["PresetDialogTitle"] = "Presets",
                ["PresetNameLabel"] = "Name",
                ["PresetSaveButton"] = "Save",
                ["PresetDeleteButton"] = "Delete",
                ["PresetLoadButton"] = "Load",
                ["PresetGlobalWarning"] = "Loading a preset here will apply settings to all loaded clips.",
                ["GamMacInfoButton"] = "Info",
                ["GamMacInfoTooltip"] = "GamMac information",
                ["GamMacInfoTitle"] = "GamMac information",
                ["GamMacCloseButton"] = "Close",
                ["ErrorTitle"] = "Error",
                ["UserGuideTitle"] = "User guide",
                ["OkButton"] = "OK",
                ["DownloadButton"] = "Download",
                ["PickFilmTitle"] = "Select a file for film",
                ["PickImgTitle"] = "Select a .tif/.tiff file for img",
                ["PickSourceTitle"] = "Select a source file (video or image)",
                ["VirtualDubNotFound"] = "VirtualDub was not found. Install VirtualDub (VirtualDub2.exe) or copy VirtualDub2.exe next to CleanScan.",
                ["AviSynthRequiredTitle"] = "AviSynth+ required",
                ["AviSynthNotDetectedBody"] = "AviSynth+ was not detected on this computer. Do you want to download it?",
                ["SelectTiffError"] = "Please select a .tif or .tiff file.",
                ["IndexNameError"] = "The file name must contain only a numeric index (e.g. 00001.tif).",
                ["NoFilmSpecified"] = "No file is set in film.",
                ["NoImgSpecified"] = "No file is set in img.",
                ["FilmNotFound"] = "The file referenced in film was not found.",
                ["ImgNotFound"] = "The file referenced in img was not found.",
                ["DropInvalidFileType"] = "Unsupported file type. Please drop a video file (.avi, .mp4, .mov…) or an image file (.tif, .tiff, .jpg…).",
                ["VdbBeginning"] = "Beginning  (Ctrl+←)",
                ["VdbPrevFrame"] = "Prev frame  (←)",
                ["VdbPlay"]      = "Play  (Space)",
                ["VdbStop"]      = "Stop",
                ["VdbNextFrame"] = "Next frame  (→)",
                ["VdbEnd"]       = "End  (Ctrl+→)",
                ["SpeedBtn"]     = "Playback speed",
                ["HalfResBtn"]   = "Half-resolution preview",
                ["DropHintBar"]  = "\u25bc  Drop your file here  \u25bc",
["RecordBtn"]    = "Record",
                ["RecordDirLabel"] = "Output directory",
                ["RecordFileLabel"] = "File name",
                ["RecordEncoderLabel"] = "Encoder",
                ["RecordContainerLabel"] = "Container",
                ["RecordQualityModeLabel"] = "Quality mode",
                ["RecordCrfLabel"] = "CRF (0 = lossless, 18 = excellent)",
                ["RecordBitrateLabel"] = "Bitrate (Mb/s)",
                ["RecordChromaLabel"] = "Chroma subsampling",
                ["RecordResizeLabel"] = "Resolution",
                ["RecordPresetLabel"] = "Preset",
                ["RecordPresetSaveBtn"] = "Save",
                ["RecordPresetLoadBtn"] = "Load",
                ["RecordPresetDeleteBtn"] = "Del",
                ["RecordDirPickTitle"] = "Select output directory",
                ["RecordStartBtn"] = "▶ Start encoding",
                ["RecordStopBtn"] = "■ Stop encoding",
                ["RecordNoDirError"] = "Please select an output directory.",
                ["RecordNoFileError"] = "Please enter a file name.",
                ["RecordNoScriptError"] = "No script available for encoding.",
                ["RecordFfmpegNotFound"] = "ffmpeg was not found. Place ffmpeg.exe next to CleanScan or install it in PATH.",
                ["RecordDoneMsg"] = "Encoding completed successfully.",
                ["RecordNoClipSelected"] = "Please select at least one clip to encode.",
                ["BatchClipListLabel"] = "Clips to encode",
                ["BatchSelectAll"] = "Select all",
                ["ShutdownCheckBox"] = "Shutdown after completion",
                ["BatchProgress"] = "Clip {0}/{1}",
                ["BatchDoneMsg"] = "Batch encoding completed. {0}/{1} clips encoded successfully.",
                ["BatchShutdownMsg"] = "Computer will shut down in 60 seconds.",
                ["TrialTitle"] = "Trial version",
                ["TrialMessage"] = "This trial version limits recording to 30 s. per clip.",
                ["ResetSettingsMenuItem"] = "Reset settings",
                ["ResetSettingsConfirm"] = "This will reset all parameters to their default values. The application will restart. Continue?",
                ["ResetSettingsTitle"] = "Reset settings",
                ["PresetModifiedTitle"] = "Preset modified",
                ["PresetModifiedMsg"] = "Save this change to preset \"{0}\"?",
                ["PresetModifiedDontAsk"] = "Don't ask me again (always save)",
                ["YesButton"] = "Yes",
                ["NoButton"] = "No",
                ["TourWelcomeTitle"] = "Welcome to CleanScan!",
                ["TourWelcomeBody"] = "This quick tour will show you the main steps to restore your film clips.",
                ["TourAddClipTitle"] = "1 \u2014 Add a clip",
                ["TourAddClipBody"] = "Click the + button or drag-and-drop a video or image sequence here to get started.",
                ["TourParamsTitle"] = "2 \u2014 Adjust parameters",
                ["TourParamsBody"] = "Expand each section (Crop, Denoise, Degrain, Sharpening\u2026) to fine-tune the restoration filters. Changes are applied in real time.",
                ["TourSliderTitle"] = "3 \u2014 Adjust a value",
                ["TourSliderBody"] = "Drag the slider or use the mouse wheel over the field to change a value. The preview updates in real time.",
                ["TourTooltipTitle"] = "4 \u2014 Tooltips",
                ["TourTooltipBody"] = "Hover over any parameter label to display a tooltip explaining what that setting does.",
                ["TourPreviewTitle"] = "5 \u2014 Preview",
                ["TourPreviewBody"] = "Use the transport controls to play, pause, and step through frames. The viewer shows your filters applied in real time.",
                ["TourRecordTitle"] = "6 \u2014 Record",
                ["TourRecordBody"] = "When you\u2019re satisfied, click Record to open the encoding panel and export your restored clip.",
                ["TourNextBtn"] = "Next \u25b6",
                ["TourPrevBtn"] = "\u25c0 Back",
                ["TourSkipBtn"] = "Skip",
                ["TourFinishBtn"] = "Get started!",
                ["GuidedTourMenuItem"] = "Guided tour",
                ["TourLanguageLabel"] = "Language:",
                ["TourClickHint"] = "\u25cb  Click the highlighted button to continue"
            },
            ["fr"] = new(StringComparer.OrdinalIgnoreCase)
            {
                ["InfosMenu"] = "Infos",
                ["UserGuideMenuItem"] = "Mode d'emploi",
                ["ScriptPreviewMenuItem"] = "Lecture du script",
                ["LanguagesMenu"] = "Langues",
                ["PresetMenuItem"] = "Preset",
                ["AboutMenuItem"] = "A propos",
                ["FeedbackMenuItem"] = "Votre retour d'expérience",
                ["SettingsMenu"] = "Réglages",
                ["ThreadsLabel"] = "Threads",
                ["SourceLoaderLabel"] = "Chargeur source",
                ["ExpandBtnTooltip"] = "Accéder aux paramètres",
                ["AllRightsReserved"] = "tous droits réservés",
                ["AboutCompany"] = "ScanFilm SNC",
                ["AboutWebsite"] = "www.scanfilm.ch",
                ["AboutVersion"] = "version d'essai — beta 4.0",
                ["PresetDialogTitle"] = "Presets",
                ["PresetNameLabel"] = "Nom",
                ["PresetSaveButton"] = "Enregistrer",
                ["PresetDeleteButton"] = "Supprimer",
                ["PresetLoadButton"] = "Charger",
                ["PresetGlobalWarning"] = "Charger un preset ici appliquera les réglages à tous les clips chargés.",
                ["GamMacInfoButton"] = "Info",
                ["GamMacInfoTooltip"] = "Informations sur GamMac",
                ["GamMacInfoTitle"] = "Informations GamMac",
                ["GamMacCloseButton"] = "Fermer",
                ["ErrorTitle"] = "Erreur",
                ["UserGuideTitle"] = "Mode d'emploi",
                ["OkButton"] = "OK",
                ["DownloadButton"] = "Télécharger",
                ["PickFilmTitle"] = "Sélectionner un fichier pour film",
                ["PickImgTitle"] = "Sélectionner un fichier .tif/.tiff pour img",
                ["PickSourceTitle"] = "Sélectionner un fichier source (vidéo ou image)",
                ["VirtualDubNotFound"] = "VirtualDub est introuvable. Installez VirtualDub (VirtualDub2.exe) ou copiez VirtualDub2.exe à côté de CleanScan.",
                ["AviSynthRequiredTitle"] = "AviSynth+ requis",
                ["AviSynthNotDetectedBody"] = "AviSynth+ n'a pas été détecté sur cet ordinateur. Voulez-vous le télécharger ?",
                ["SelectTiffError"] = "Veuillez sélectionner un fichier .tif ou .tiff.",
                ["IndexNameError"] = "Le nom du fichier doit contenir uniquement un index numérique (ex. 00001.tif).",
                ["NoFilmSpecified"] = "Aucun fichier n'est défini dans film.",
                ["NoImgSpecified"] = "Aucun fichier n'est défini dans img.",
                ["FilmNotFound"] = "Le fichier référencé dans film est introuvable.",
                ["ImgNotFound"] = "Le fichier référencé dans img est introuvable.",
                ["DropInvalidFileType"] = "Type de fichier non pris en charge. Déposez un fichier vidéo (.avi, .mp4, .mov…) ou une image (.tif, .tiff, .jpg…).",
                ["VdbBeginning"] = "Début  (Ctrl+←)",
                ["VdbPrevFrame"] = "Image précédente  (←)",
                ["VdbPlay"]      = "Lecture  (Space)",
                ["VdbStop"]      = "Arrêt",
                ["VdbNextFrame"] = "Image suivante  (→)",
                ["VdbEnd"]       = "Fin  (Ctrl+→)",
                ["SpeedBtn"]     = "Vitesse de lecture",
                ["HalfResBtn"]   = "Aperçu demi-résolution",
                ["DropHintBar"]  = "\u25bc  Glisse ton fichier ici  \u25bc",
["RecordBtn"]    = "Enregistrer",
                ["RecordDirLabel"] = "Répertoire de sortie",
                ["RecordFileLabel"] = "Nom du fichier",
                ["RecordEncoderLabel"] = "Encodeur",
                ["RecordContainerLabel"] = "Conteneur",
                ["RecordQualityModeLabel"] = "Mode qualité",
                ["RecordCrfLabel"] = "CRF (0 = sans perte, 18 = excellent)",
                ["RecordBitrateLabel"] = "Débit (Mb/s)",
                ["RecordChromaLabel"] = "Sous-échantillonnage chroma",
                ["RecordResizeLabel"] = "Résolution",
                ["RecordPresetLabel"] = "Preset",
                ["RecordPresetSaveBtn"] = "Sauver",
                ["RecordPresetLoadBtn"] = "Charger",
                ["RecordPresetDeleteBtn"] = "Suppr",
                ["RecordDirPickTitle"] = "Sélectionner le répertoire de sortie",
                ["RecordStartBtn"] = "▶ Lancer l'encodage",
                ["RecordStopBtn"] = "■ Arrêter l'encodage",
                ["RecordNoDirError"] = "Veuillez sélectionner un répertoire de sortie.",
                ["RecordNoFileError"] = "Veuillez saisir un nom de fichier.",
                ["RecordNoScriptError"] = "Aucun script disponible pour l'encodage.",
                ["RecordFfmpegNotFound"] = "ffmpeg est introuvable. Placez ffmpeg.exe à côté de CleanScan ou installez-le dans le PATH.",
                ["RecordDoneMsg"] = "Encodage terminé avec succès.",
                ["RecordNoClipSelected"] = "Veuillez sélectionner au moins un clip à encoder.",
                ["BatchClipListLabel"] = "Clips à encoder",
                ["BatchSelectAll"] = "Tout sélectionner",
                ["ShutdownCheckBox"] = "Éteindre après encodage",
                ["BatchProgress"] = "Clip {0}/{1}",
                ["BatchDoneMsg"] = "Encodage par lot terminé. {0}/{1} clips encodés avec succès.",
                ["BatchShutdownMsg"] = "L'ordinateur va s'éteindre dans 60 secondes.",
                ["TrialTitle"] = "Version d'essai",
                ["TrialMessage"] = "Cette version d'essai limite l'enregistrement à 30 s. par clip.",
                ["ResetSettingsMenuItem"] = "Réinitialiser les paramètres",
                ["ResetSettingsConfirm"] = "Ceci va réinitialiser tous les paramètres à leurs valeurs par défaut. L'application va redémarrer. Continuer ?",
                ["ResetSettingsTitle"] = "Réinitialisation",
                ["PresetModifiedTitle"] = "Preset modifié",
                ["PresetModifiedMsg"] = "Enregistrer cette modification dans le preset « {0} » ?",
                ["PresetModifiedDontAsk"] = "Ne plus me demander (toujours enregistrer)",
                ["YesButton"] = "Oui",
                ["NoButton"] = "Non",
                ["TourWelcomeTitle"] = "Bienvenue dans CleanScan !",
                ["TourWelcomeBody"] = "Ce petit tour vous pr\u00e9sente les \u00e9tapes principales pour restaurer vos clips.",
                ["TourAddClipTitle"] = "1 \u2014 Ajouter un clip",
                ["TourAddClipBody"] = "Cliquez sur le bouton + ou glissez-d\u00e9posez un fichier vid\u00e9o ou une s\u00e9quence d\u2019images ici pour commencer.",
                ["TourParamsTitle"] = "2 \u2014 R\u00e9gler les param\u00e8tres",
                ["TourParamsBody"] = "D\u00e9pliez chaque section (Recadrage, D\u00e9bruitage, Degrain, Nettet\u00e9\u2026) pour ajuster les filtres de restauration. Les modifications sont appliqu\u00e9es en temps r\u00e9el.",
                ["TourSliderTitle"] = "3 \u2014 Modifier une valeur",
                ["TourSliderBody"] = "Faites glisser le curseur ou utilisez la molette de la souris sur le champ pour ajuster une valeur. L\u2019aper\u00e7u se met \u00e0 jour en temps r\u00e9el.",
                ["TourTooltipTitle"] = "4 \u2014 Info-bulles",
                ["TourTooltipBody"] = "Survolez le libell\u00e9 d\u2019un param\u00e8tre pour afficher une info-bulle d\u00e9taillant le r\u00f4le de ce r\u00e9glage.",
                ["TourPreviewTitle"] = "5 \u2014 Pr\u00e9visualiser",
                ["TourPreviewBody"] = "Utilisez les contr\u00f4les de lecture pour lire, mettre en pause et avancer image par image. Le lecteur affiche vos filtres en temps r\u00e9el.",
                ["TourRecordTitle"] = "6 \u2014 Enregistrer",
                ["TourRecordBody"] = "Quand le r\u00e9sultat vous convient, cliquez sur Enregistrer pour ouvrir le panneau d\u2019encodage et exporter votre clip restaur\u00e9.",
                ["TourNextBtn"] = "Suivant \u25b6",
                ["TourPrevBtn"] = "\u25c0 Retour",
                ["TourSkipBtn"] = "Passer",
                ["TourFinishBtn"] = "C\u2019est parti !",
                ["GuidedTourMenuItem"] = "Visite guidée",
                ["TourLanguageLabel"] = "Langue :",
                ["TourClickHint"] = "\u25cb  Cliquez sur le bouton en surbrillance pour continuer"
            },
            ["de"] = new(StringComparer.OrdinalIgnoreCase)
            {
                ["InfosMenu"] = "Infos",
                ["UserGuideMenuItem"] = "Benutzerhandbuch",
                ["ScriptPreviewMenuItem"] = "Script-Vorschau",
                ["LanguagesMenu"] = "Sprachen",
                ["PresetMenuItem"] = "Preset",
                ["AboutMenuItem"] = "Über",
                ["FeedbackMenuItem"] = "Feedback",
                ["SettingsMenu"] = "Einstellungen",
                ["ThreadsLabel"] = "Threads",
                ["SourceLoaderLabel"] = "Quellenlader",
                ["ExpandBtnTooltip"] = "Parameter anzeigen",
                ["AllRightsReserved"] = "alle Rechte vorbehalten",
                ["AboutCompany"] = "ScanFilm SNC",
                ["AboutWebsite"] = "www.scanfilm.ch",
                ["AboutVersion"] = "Testversion — Beta 4.0",
                ["PresetDialogTitle"] = "Presets",
                ["PresetNameLabel"] = "Name",
                ["PresetSaveButton"] = "Speichern",
                ["PresetDeleteButton"] = "Löschen",
                ["PresetLoadButton"] = "Laden",
                ["PresetGlobalWarning"] = "Ein Preset hier zu laden wendet die Einstellungen auf alle geladenen Clips an.",
                ["GamMacInfoButton"] = "Info",
                ["GamMacInfoTooltip"] = "GamMac-Informationen",
                ["GamMacInfoTitle"] = "GamMac-Informationen",
                ["GamMacCloseButton"] = "Schließen",
                ["ErrorTitle"] = "Fehler",
                ["UserGuideTitle"] = "Benutzerhandbuch",
                ["OkButton"] = "OK",
                ["DownloadButton"] = "Herunterladen",
                ["PickFilmTitle"] = "Datei für film auswählen",
                ["PickImgTitle"] = "Eine .tif/.tiff-Datei für img auswählen",
                ["PickSourceTitle"] = "Quelldatei auswählen (Video oder Bild)",
                ["VirtualDubNotFound"] = "VirtualDub wurde nicht gefunden. Installieren Sie VirtualDub (VirtualDub2.exe) oder kopieren Sie VirtualDub2.exe neben CleanScan.",
                ["AviSynthRequiredTitle"] = "AviSynth+ erforderlich",
                ["AviSynthNotDetectedBody"] = "AviSynth+ wurde auf diesem Computer nicht erkannt. Möchten Sie es herunterladen?",
                ["SelectTiffError"] = "Bitte wählen Sie eine .tif- oder .tiff-Datei aus.",
                ["IndexNameError"] = "Der Dateiname darf nur einen numerischen Index enthalten (z. B. 00001.tif).",
                ["NoFilmSpecified"] = "In film ist keine Datei gesetzt.",
                ["NoImgSpecified"] = "In img ist keine Datei gesetzt.",
                ["FilmNotFound"] = "Die in film referenzierte Datei wurde nicht gefunden.",
                ["ImgNotFound"] = "Die in img referenzierte Datei wurde nicht gefunden.",
                ["DropInvalidFileType"] = "Nicht unterstützter Dateityp. Bitte eine Videodatei (.avi, .mp4, .mov…) oder Bilddatei (.tif, .tiff, .jpg…) ablegen.",
                ["VdbBeginning"] = "Anfang  (Ctrl+←)",
                ["VdbPrevFrame"] = "Vorheriges Bild  (←)",
                ["VdbPlay"]      = "Abspielen  (Space)",
                ["VdbStop"]      = "Stopp",
                ["VdbNextFrame"] = "Nächstes Bild  (→)",
                ["VdbEnd"]       = "Ende  (Ctrl+→)",
                ["SpeedBtn"]     = "Wiedergabegeschwindigkeit",
                ["HalfResBtn"]   = "Vorschau halbe Auflösung",
                ["DropHintBar"]  = "\u25bc  Datei hier ablegen  \u25bc",
["RecordBtn"]    = "Aufnahme",
                ["RecordDirLabel"] = "Ausgabeverzeichnis",
                ["RecordFileLabel"] = "Dateiname",
                ["RecordEncoderLabel"] = "Encoder",
                ["RecordContainerLabel"] = "Container",
                ["RecordQualityModeLabel"] = "Qualitätsmodus",
                ["RecordCrfLabel"] = "CRF (0 = verlustfrei, 18 = ausgezeichnet)",
                ["RecordBitrateLabel"] = "Bitrate (Mb/s)",
                ["RecordChromaLabel"] = "Chroma-Unterabtastung",
                ["RecordResizeLabel"] = "Auflösung",
                ["RecordPresetLabel"] = "Preset",
                ["RecordPresetSaveBtn"] = "Speichern",
                ["RecordPresetLoadBtn"] = "Laden",
                ["RecordPresetDeleteBtn"] = "Lösch",
                ["RecordDirPickTitle"] = "Ausgabeverzeichnis auswählen",
                ["RecordStartBtn"] = "▶ Kodierung starten",
                ["RecordStopBtn"] = "■ Kodierung stoppen",
                ["RecordNoDirError"] = "Bitte wählen Sie ein Ausgabeverzeichnis.",
                ["RecordNoFileError"] = "Bitte geben Sie einen Dateinamen ein.",
                ["RecordNoScriptError"] = "Kein Skript für die Kodierung verfügbar.",
                ["RecordFfmpegNotFound"] = "ffmpeg wurde nicht gefunden. Platzieren Sie ffmpeg.exe neben CleanScan oder installieren Sie es im PATH.",
                ["RecordDoneMsg"] = "Kodierung erfolgreich abgeschlossen.",
                ["RecordNoClipSelected"] = "Bitte wählen Sie mindestens einen Clip zum Kodieren.",
                ["BatchClipListLabel"] = "Zu kodierende Clips",
                ["BatchSelectAll"] = "Alle auswählen",
                ["ShutdownCheckBox"] = "Nach Abschluss herunterfahren",
                ["BatchProgress"] = "Clip {0}/{1}",
                ["BatchDoneMsg"] = "Stapelkodierung abgeschlossen. {0}/{1} Clips erfolgreich kodiert.",
                ["BatchShutdownMsg"] = "Der Computer wird in 60 Sekunden heruntergefahren.",
                ["TrialTitle"] = "Testversion",
                ["TrialMessage"] = "Diese Testversion begrenzt die Aufnahme auf 30 s. pro Clip.",
                ["ResetSettingsMenuItem"] = "Einstellungen zurücksetzen",
                ["ResetSettingsConfirm"] = "Alle Parameter werden auf die Standardwerte zurückgesetzt. Die Anwendung wird neu gestartet. Fortfahren?",
                ["ResetSettingsTitle"] = "Zurücksetzen",
                ["PresetModifiedTitle"] = "Preset geändert",
                ["PresetModifiedMsg"] = "Diese \u00c4nderung im Preset \u201e{0}\u201c speichern?",
                ["PresetModifiedDontAsk"] = "Nicht mehr fragen (immer speichern)",
                ["YesButton"] = "Ja",
                ["NoButton"] = "Nein",
                ["TourWelcomeTitle"] = "Willkommen bei CleanScan!",
                ["TourWelcomeBody"] = "Diese kurze Tour zeigt Ihnen die wichtigsten Schritte zur Restaurierung Ihrer Filmclips.",
                ["TourAddClipTitle"] = "1 \u2014 Clip hinzuf\u00fcgen",
                ["TourAddClipBody"] = "Klicken Sie auf + oder ziehen Sie eine Video- oder Bildsequenz hierher, um zu beginnen.",
                ["TourParamsTitle"] = "2 \u2014 Parameter anpassen",
                ["TourParamsBody"] = "Klappen Sie die Bereiche auf (Zuschnitt, Entrauschen, Degrain, Sch\u00e4rfe\u2026), um die Filter anzupassen. \u00c4nderungen werden in Echtzeit angezeigt.",
                ["TourSliderTitle"] = "3 \u2014 Wert anpassen",
                ["TourSliderBody"] = "Ziehen Sie den Schieberegler oder verwenden Sie das Mausrad \u00fcber dem Feld, um einen Wert zu \u00e4ndern. Die Vorschau wird in Echtzeit aktualisiert.",
                ["TourTooltipTitle"] = "4 \u2014 Tooltips",
                ["TourTooltipBody"] = "Fahren Sie mit der Maus \u00fcber ein Parameterlabel, um einen Tooltip mit der Beschreibung dieser Einstellung anzuzeigen.",
                ["TourPreviewTitle"] = "5 \u2014 Vorschau",
                ["TourPreviewBody"] = "Verwenden Sie die Wiedergabesteuerung zum Abspielen, Pausieren und Einzelbildschritten. Der Viewer zeigt Ihre Filter in Echtzeit.",
                ["TourRecordTitle"] = "6 \u2014 Aufnahme",
                ["TourRecordBody"] = "Wenn Sie zufrieden sind, klicken Sie auf Aufnahme, um den Clip zu exportieren.",
                ["TourNextBtn"] = "Weiter \u25b6",
                ["TourPrevBtn"] = "\u25c0 Zur\u00fcck",
                ["TourSkipBtn"] = "\u00dcberspringen",
                ["TourFinishBtn"] = "Los geht\u2019s!",
                ["GuidedTourMenuItem"] = "Geführte Tour",
                ["TourLanguageLabel"] = "Sprache:",
                ["TourClickHint"] = "\u25cb  Klicken Sie auf die hervorgehobene Schaltfläche, um fortzufahren"
            },
            ["es"] = new(StringComparer.OrdinalIgnoreCase)
            {
                ["InfosMenu"] = "Infos",
                ["UserGuideMenuItem"] = "Guía del usuario",
                ["ScriptPreviewMenuItem"] = "Vista previa del script",
                ["LanguagesMenu"] = "Idiomas",
                ["PresetMenuItem"] = "Preset",
                ["AboutMenuItem"] = "Acerca de",
                ["FeedbackMenuItem"] = "Comentarios",
                ["SettingsMenu"] = "Ajustes",
                ["ThreadsLabel"] = "Threads",
                ["SourceLoaderLabel"] = "Cargador de fuente",
                ["ExpandBtnTooltip"] = "Ver parámetros",
                ["AllRightsReserved"] = "todos los derechos reservados",
                ["AboutCompany"] = "ScanFilm SNC",
                ["AboutWebsite"] = "www.scanfilm.ch",
                ["AboutVersion"] = "versión de prueba — beta 4.0",
                ["PresetDialogTitle"] = "Presets",
                ["PresetNameLabel"] = "Nombre",
                ["PresetSaveButton"] = "Guardar",
                ["PresetDeleteButton"] = "Eliminar",
                ["PresetLoadButton"] = "Cargar",
                ["PresetGlobalWarning"] = "Cargar un preset aquí aplicará los ajustes a todos los clips cargados.",
                ["GamMacInfoButton"] = "Info",
                ["GamMacInfoTooltip"] = "Información de GamMac",
                ["GamMacInfoTitle"] = "Información de GamMac",
                ["GamMacCloseButton"] = "Cerrar",
                ["ErrorTitle"] = "Error",
                ["UserGuideTitle"] = "Guía del usuario",
                ["OkButton"] = "OK",
                ["DownloadButton"] = "Descargar",
                ["PickFilmTitle"] = "Seleccionar un archivo para film",
                ["PickImgTitle"] = "Seleccionar un archivo .tif/.tiff para img",
                ["PickSourceTitle"] = "Seleccionar un archivo fuente (vídeo o imagen)",
                ["VirtualDubNotFound"] = "No se encontró VirtualDub. Instale VirtualDub (VirtualDub2.exe) o copie VirtualDub2.exe junto a CleanScan.",
                ["AviSynthRequiredTitle"] = "AviSynth+ requerido",
                ["AviSynthNotDetectedBody"] = "AviSynth+ no se detectó en este equipo. ¿Desea descargarlo?",
                ["SelectTiffError"] = "Seleccione un archivo .tif o .tiff.",
                ["IndexNameError"] = "El nombre del archivo debe contener solo un índice numérico (p. ej. 00001.tif).",
                ["NoFilmSpecified"] = "No hay ningún archivo definido en film.",
                ["NoImgSpecified"] = "No hay ningún archivo definido en img.",
                ["FilmNotFound"] = "No se encontró el archivo referenciado en film.",
                ["ImgNotFound"] = "No se encontró el archivo referenciado en img.",
                ["DropInvalidFileType"] = "Tipo de archivo no compatible. Suelte un archivo de vídeo (.avi, .mp4, .mov…) o imagen (.tif, .tiff, .jpg…).",
                ["VdbBeginning"] = "Inicio  (Ctrl+←)",
                ["VdbPrevFrame"] = "Fotograma anterior  (←)",
                ["VdbPlay"]      = "Reproducir  (Space)",
                ["VdbStop"]      = "Detener",
                ["VdbNextFrame"] = "Fotograma siguiente  (→)",
                ["VdbEnd"]       = "Fin  (Ctrl+→)",
                ["SpeedBtn"]     = "Velocidad de reproducción",
                ["HalfResBtn"]   = "Vista previa a media resolución",
                ["DropHintBar"]  = "\u25bc  Suelta tu archivo aquí  \u25bc",
["RecordBtn"]    = "Grabar",
                ["RecordDirLabel"] = "Directorio de salida",
                ["RecordFileLabel"] = "Nombre del archivo",
                ["RecordEncoderLabel"] = "Codificador",
                ["RecordContainerLabel"] = "Contenedor",
                ["RecordQualityModeLabel"] = "Modo de calidad",
                ["RecordCrfLabel"] = "CRF (0 = sin pérdida, 18 = excelente)",
                ["RecordBitrateLabel"] = "Tasa de bits (Mb/s)",
                ["RecordChromaLabel"] = "Submuestreo de croma",
                ["RecordResizeLabel"] = "Resolución",
                ["RecordPresetLabel"] = "Preset",
                ["RecordPresetSaveBtn"] = "Guardar",
                ["RecordPresetLoadBtn"] = "Cargar",
                ["RecordPresetDeleteBtn"] = "Borrar",
                ["RecordDirPickTitle"] = "Seleccionar directorio de salida",
                ["RecordStartBtn"] = "▶ Iniciar codificación",
                ["RecordStopBtn"] = "■ Detener codificación",
                ["RecordNoDirError"] = "Seleccione un directorio de salida.",
                ["RecordNoFileError"] = "Introduzca un nombre de archivo.",
                ["RecordNoScriptError"] = "No hay script disponible para la codificación.",
                ["RecordFfmpegNotFound"] = "No se encontró ffmpeg. Coloque ffmpeg.exe junto a CleanScan o instálelo en el PATH.",
                ["RecordDoneMsg"] = "Codificación completada con éxito.",
                ["RecordNoClipSelected"] = "Seleccione al menos un clip para codificar.",
                ["BatchClipListLabel"] = "Clips a codificar",
                ["BatchSelectAll"] = "Seleccionar todo",
                ["ShutdownCheckBox"] = "Apagar después de completar",
                ["BatchProgress"] = "Clip {0}/{1}",
                ["BatchDoneMsg"] = "Codificación por lotes completada. {0}/{1} clips codificados con éxito.",
                ["BatchShutdownMsg"] = "El ordenador se apagará en 60 segundos.",
                ["TrialTitle"] = "Versión de prueba",
                ["TrialMessage"] = "Esta versión de prueba limita la grabación a 30 s. por clip.",
                ["ResetSettingsMenuItem"] = "Restablecer ajustes",
                ["ResetSettingsConfirm"] = "Se restablecerán todos los parámetros a sus valores predeterminados. La aplicación se reiniciará. ¿Continuar?",
                ["ResetSettingsTitle"] = "Restablecer",
                ["PresetModifiedTitle"] = "Preset modificado",
                ["PresetModifiedMsg"] = "¿Guardar este cambio en el preset «{0}»?",
                ["PresetModifiedDontAsk"] = "No volver a preguntar (guardar siempre)",
                ["YesButton"] = "Sí",
                ["NoButton"] = "No",
                ["TourWelcomeTitle"] = "\u00a1Bienvenido a CleanScan!",
                ["TourWelcomeBody"] = "Este breve recorrido le mostrar\u00e1 los pasos principales para restaurar sus clips de pel\u00edcula.",
                ["TourAddClipTitle"] = "1 \u2014 A\u00f1adir un clip",
                ["TourAddClipBody"] = "Haga clic en + o arrastre y suelte un archivo de v\u00eddeo o secuencia de im\u00e1genes aqu\u00ed para empezar.",
                ["TourParamsTitle"] = "2 \u2014 Ajustar par\u00e1metros",
                ["TourParamsBody"] = "Despliegue cada secci\u00f3n (Recorte, Ruido, Degrain, Nitidez\u2026) para ajustar los filtros. Los cambios se aplican en tiempo real.",
                ["TourPreviewTitle"] = "5 \u2014 Vista previa",
                ["TourPreviewBody"] = "Use los controles de reproducci\u00f3n para reproducir, pausar y avanzar fotograma a fotograma.",
                ["TourSliderTitle"] = "3 \u2014 Ajustar un valor",
                ["TourSliderBody"] = "Arrastre el control deslizante o use la rueda del rat\u00f3n sobre el campo para cambiar un valor. La vista previa se actualiza en tiempo real.",
                ["TourTooltipTitle"] = "4 \u2014 Tooltips",
                ["TourTooltipBody"] = "Pase el rat\u00f3n sobre la etiqueta de un par\u00e1metro para ver un tooltip que describe la funci\u00f3n de ese ajuste.",
                ["TourRecordTitle"] = "6 \u2014 Grabar",
                ["TourRecordBody"] = "Cuando est\u00e9 satisfecho, haga clic en Grabar para exportar su clip restaurado.",
                ["TourNextBtn"] = "Siguiente \u25b6",
                ["TourPrevBtn"] = "\u25c0 Atr\u00e1s",
                ["TourSkipBtn"] = "Saltar",
                ["TourFinishBtn"] = "\u00a1Empezar!",
                ["GuidedTourMenuItem"] = "Visita guiada",
                ["TourLanguageLabel"] = "Idioma:",
                ["TourClickHint"] = "\u25cb  Haga clic en el botón resaltado para continuar"
            }
        };

        public string CurrentLanguageCode { get; private set; } = GetOsLanguageCodeOrEnglish();

        public static string GetOsLanguageCodeOrEnglish()
        {
            var osTwoLetter = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
            return UiTexts.ContainsKey(osTwoLetter) ? osTwoLetter : "en";
        }

        public void SetLanguage(string languageCode)
        {
            CurrentLanguageCode = UiTexts.ContainsKey(languageCode) ? languageCode : "en";
        }

        public string GetUiText(string key)
        {
            if (UiTexts.TryGetValue(CurrentLanguageCode, out var map) && map.TryGetValue(key, out var text))
            {
                return text;
            }

            if (UiTexts.TryGetValue("en", out var enMap) && enMap.TryGetValue(key, out var enText))
            {
                return enText;
            }

            return key;
        }

        public string GetUiText(string key, params object[] args)
        {
            var fmt = GetUiText(key);
            return args.Length == 0 ? fmt : string.Format(CultureInfo.CurrentCulture, fmt, args);
        }

        public string GetLocalizedText(string fr, string en)
        {
            return string.Equals(CurrentLanguageCode, "fr", StringComparison.OrdinalIgnoreCase) ? fr : en;
        }
    }
}
