"""Generate the 4 ScanRestore User Guide PDFs (en, fr, de, es) using fpdf2."""

import os
from fpdf import FPDF

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(BASE_DIR, "Users Guide")
os.makedirs(OUT_DIR, exist_ok=True)

# ─── Guide content per language ──────────────────────────────────────────────

GUIDES = {
    "fr": {
        "title": "C L E A N S C A N",
        "subtitle": "Guide de l'utilisateur",
        "company": "ScanFilm SNC",
        "website": "www.scanfilm.ch",
        "version": "Version d'essai - Beta 5.0",
        "toc_title": "TABLE DES MATIERES",
        "sections": [
            ("1. Presentation", [
                "ScanRestore est un logiciel de restauration de films argentiques numerises (8 mm, Super 8,",
                "9,5 mm, 16 mm). Il permet de :",
                "",
                "  - Reduire le grain de pellicule",
                "  - Supprimer poussieres et rayures",
                "  - Corriger luminosite, contraste et couleurs",
                "  - Recadrer l'image",
                "  - Renforcer la nettete",
                "",
                "Le logiciel genere un script AviSynth+ optimise et offre une previsualisation en temps reel",
                "via un lecteur video integre (libmpv). L'encodage final est assure par FFmpeg.",
            ]),
            ("2. Prerequis et installation", [
                "Systeme requis :",
                "  - Windows 10 ou 11 (64 bits)",
                "  - 4 Go de RAM minimum (8 Go recommande)",
                "  - Espace disque suffisant pour les fichiers source et les rendus",
                "",
                "Composants :",
                "  - AviSynth+ 64 bits doit etre installe. Si absent, ScanRestore le detecte au demarrage",
                "    et propose un lien de telechargement. Une version embarquee est utilisee en secours.",
                "  - FFmpeg est fourni avec l'application (dossier Plugins/ffmpeg/).",
                "  - Le lecteur mpv est fourni avec l'application (dossier mpv/).",
                "",
                "Aucune installation supplementaire n'est requise. Il suffit de decompresser l'archive",
                "et de lancer l'executable ScanRestore.exe.",
            ]),
            ("3. Interface generale", [
                "L'interface est organisee en trois zones :",
                "",
                "ZONE SUPERIEURE",
                "  Barre de menus : Infos, Preset, Settings, Feedback, Language, A propos.",
                "  Barre de source : champs de selection du fichier source, mode image, FPS.",
                "  Onglets clips : chaque clip charge apparait sous forme d'onglet.",
                "  Barre de transport : commandes de lecture, barre de progression, bouton Record.",
                "",
                "ZONE CENTRALE",
                "  Lecteur video mpv : affiche la previsualisation du script AviSynth en temps reel.",
                "",
                "ZONE INFERIEURE",
                "  Panneau de filtres : divise en deux colonnes separees par un separateur.",
            ]),
            ("4. Selection de la source", [
                "Fichier video :",
                "  Glissez-deposez un fichier video sur la zone de lecture, ou cliquez sur le champ source.",
                "  Formats supportes : .avi .mp4 .mov .mkv .wmv .m4v .mpeg .mpg .webm",
                "",
                "Sequence d'images :",
                "  Activez le mode image, puis renseignez le chemin du dossier dans le champ img.",
                "  Formats supportes : .tif .tiff .jpg .jpeg .png .bmp",
                "",
                "Cadence de lecture (FPS) :",
                "  16 fps (8 mm), 18 fps (Super 8), 24 fps (16 mm).",
                "",
                "Multi-clips :",
                "  Vous pouvez charger plusieurs fichiers. Chaque clip dispose de ses propres reglages.",
            ]),
            ("5. Lecteur video et navigation", [
                "Le lecteur integre affiche le resultat du script AviSynth en temps reel.",
                "",
                "Raccourcis clavier :",
                "  Espace           Lecture / Pause",
                "  Fleche gauche    Image precedente",
                "  Fleche droite    Image suivante",
                "  Ctrl + Gauche    Aller au debut",
                "  Ctrl + Droite    Aller a la fin",
                "",
                "Barre de transport :",
                "  |<  Debut     <<  Precedent     >  Lecture     >>  Suivant     >|  Fin",
                "  1x  Vitesse (0.25x, 0.5x, 1x)     1/2  Demi-resolution",
            ]),
            ("6. Panneau de filtres", [
                "Le panneau inferieur est divise en deux colonnes :",
                "  Colonne gauche : boutons d'activation (ON/OFF)",
                "  Colonne droite : parametres detailles",
                "",
                "Filtres disponibles :",
                "  - Crop : recadrage (supprime des pixels sur les bords)",
                "  - Degrain : reduction temporelle du grain (MVTools2)",
                "  - Denoise : suppression des poussieres et rayures",
                "  - Luma : ajustement luminosite, contraste, saturation, teinte, gamma",
                "  - GamMac : correction colorimetrique automatique",
                "  - Sharpen : renforcement de la nettete",
                "",
                "Survolez chaque parametre pour afficher une infobulle.",
            ]),
            ("7. Prereglages (Presets)", [
                "Le menu Preset permet de sauvegarder et restaurer vos configurations de filtres.",
                "",
                "  Sauvegarder : enregistre les reglages actuels sous un nom",
                "  Charger : applique un preset existant",
                "  Supprimer : efface un preset",
                "",
                "Les champs source, film, img, start, end et crop ne sont PAS inclus dans les presets.",
                "Emplacement : %AppData%\\AvyscanLab\\presets.json",
            ]),
            ("8. Filtres personnalises (Custom)", [
                "ScanRestore permet de creer vos propres filtres AviSynth et de les integrer dans le",
                "pipeline de restauration. Les filtres personnalises sont affiches dans la section",
                "CUSTOM du panneau de filtres (colonne gauche).",
                "",
                "CREER UN FILTRE PERSONNALISE",
                "",
                "  1. Cliquez sur le bouton \"+\" a droite du titre CUSTOM dans le panneau de filtres.",
                "     Le formulaire de filtre personnalise s'ouvre.",
                "",
                "  2. Renseignez le nom du filtre et la position dans le pipeline :",
                "     - BeforePipeline : avant tous les filtres",
                "     - AfterGamMac : apres la correction colorimetrique",
                "     - AfterDenoise : apres la suppression des poussieres",
                "     - AfterDegrain : apres la reduction du grain",
                "     - AfterLuma : apres les niveaux de luminosite",
                "     - AfterSharpen : apres la nettete (fin du pipeline)",
                "",
                "  3. Si votre filtre necessite un plugin AviSynth externe (.dll), cliquez sur",
                "     \"+ Ajouter DLL...\" pour l'ajouter. Les DLLs sont chargees via TryLoadPlugin()",
                "     et les doublons sont automatiquement elimines.",
                "",
                "  4. Ecrivez le code AviSynth dans l'editeur. Utilisez \"c\" comme variable clip :",
                "         c = MonFiltre(c, force={sigma})",
                "     Les mots entre accolades {nom} sont detectes automatiquement comme parametres.",
                "",
                "  5. Pour chaque parametre detecte, configurez le type de controle :",
                "     - slider : curseur avec Min, Max, Step et Defaut",
                "     - combo : liste deroulante avec valeurs separees par virgule",
                "     - checkbox : case a cocher avec valeurs On/Off",
                "     - text : champ texte libre",
                "",
                "  6. Utilisez le bouton \"Apercu\" pour tester le filtre en temps reel sans quitter",
                "     le formulaire.",
                "",
                "  7. Cliquez sur \"Enregistrer\" pour sauvegarder.",
                "",
                "UTILISER UN FILTRE PERSONNALISE",
                "",
                "  Le filtre apparait dans la section CUSTOM avec un bouton ON/OFF. Cliquez dessus",
                "  pour l'activer. Le bouton fleche (>) ouvre le panneau de parametres. Le bouton",
                "  crayon ouvre le formulaire d'edition.",
                "",
                "EXPORTER / IMPORTER UN FILTRE",
                "",
                "  Exporter : dans le formulaire d'edition, cliquez sur \"Exporter\". Le filtre est",
                "  sauvegarde dans un fichier .json que vous pouvez partager.",
                "",
                "  Importer : dans le panneau de filtres, cliquez sur le bouton fleche vers le bas",
                "  a cote du \"+\" dans la section CUSTOM. Selectionnez un fichier .json exporte.",
                "  Les filtres importes recoivent un nouvel identifiant.",
                "",
                "  Note : les chemins DLL sont absolus. Si le filtre utilise un plugin externe,",
                "  assurez-vous que la DLL est presente sur la machine cible.",
                "",
                "SUPPRIMER UN FILTRE",
                "",
                "  Ouvrez le formulaire d'edition (bouton crayon) et cliquez sur \"Supprimer\".",
                "",
                "Emplacement : %AppData%\\AvyscanLab\\custom_filters.json",
            ]),
            ("9. Encodage et rendu", [
                "Cliquez sur le bouton REC dans la barre de transport pour ouvrir le panneau d'encodage.",
                "",
                "  Etape 1 : Cochez les clips a encoder dans la liste.",
                "  Etape 2 : Selectionnez le dossier de destination.",
                "  Etape 3 : Choisissez l'encodeur (x264, x265, FFV1, UT Video, ProRes, TIFF, PNG).",
                "  Etape 4 : Selectionnez le conteneur (MKV, MP4, AVI, MOV).",
                "  Etape 5 : Ajustez les parametres (CRF/Bitrate, Chroma, Resolution).",
                "",
                "Presets d'encodage : sauvegardez vos combinaisons frequentes.",
                "Emplacement : %AppData%\\AvyscanLab\\encoding_presets.json",
                "",
                "Option \"Eteindre apres encodage\" disponible pour les encodages longs.",
            ]),
            ("10. Reglages de l'application", [
                "Menu Reglages :",
                "  Threads : nombre de threads AviSynth",
                "  Chargeur source : Auto, FFMS2, L-SMASH, LWLibav",
                "  Reset settings : reinitialise tous les reglages par defaut",
                "",
                "Menu Langue : Francais, English, Deutsch, Espanol.",
            ]),
            ("11. Apercu du script", [
                "Menu Infos > Apercu du script ouvre une fenetre affichant le contenu complet du",
                "fichier ScriptUser.avs genere par ScanRestore.",
                "Le bouton \"Recharger\" relit le fichier depuis le disque.",
            ]),
            ("12. Retour d'experience (Feedback)", [
                "Le menu Feedback ouvre un formulaire de contact integre permettant d'envoyer :",
                "  - Un signalement de bug",
                "  - Une demande de fonctionnalite",
                "  - Un avis general avec notation",
            ]),
            ("13. Workflow recommande", [
                "  1. Ouvrez votre source (glisser-deposer ou champ source).",
                "  2. Naviguez jusqu'a une image representative.",
                "  3. Activez les filtres un par un :",
                "     a) Crop - Supprimez les bordures noires",
                "     b) Degrain - Preset \"standard\", puis ajustez thSAD",
                "     c) Denoise - Supprimez les poussieres",
                "     d) Luma - Ajustez luminosite et contraste",
                "     e) GamMac - Corrigez les derives de couleur",
                "     f) Sharpen - Renforcez la nettete en dernier",
                "     g) Custom - Ajoutez vos filtres personnalises si necessaire",
                "  4. Sauvegardez votre configuration en preset.",
                "  5. Ouvrez le panneau Record et lancez l'encodage.",
            ]),
            ("14. Astuces et raccourcis", [
                "  - La molette de souris sur les champs numeriques ajuste la valeur par pas.",
                "  - Le mode demi-resolution accelere la previsualisation.",
                "  - Tous les parametres sont sauvegardes automatiquement.",
                "  - La position et la taille de la fenetre sont memorisees.",
                "  - Les infobulles (survol) affichent les plages et des conseils.",
                "  - Le glisser-deposer de plusieurs fichiers cree un clip par fichier.",
                "  - Les filtres personnalises peuvent etre partages via export/import JSON.",
            ]),
            ("15. Fichiers et emplacements", [
                "  ScriptUser.avs              Dossier de l'exe",
                "  ScriptMaster.xx.avs         Dossier de l'exe",
                "  ScriptRender.avs            Dossier de l'exe",
                "  presets.json                %AppData%\\AvyscanLab",
                "  encoding_presets.json       %AppData%\\AvyscanLab",
                "  custom_filters.json         %AppData%\\AvyscanLab",
                "  window_settings.json        %AppData%\\AvyscanLab",
                "  session.json                %AppData%\\AvyscanLab",
                "  Plugins/                    Dossier de l'exe",
                "  mpv/                        Dossier de l'exe",
            ]),
            ("16. Contenu de l'application", [
                "Arborescence des fichiers distribues avec ScanRestore :",
                "",
                "  AvyscanLab.exe                         Executable principal",
                "  ScriptMaster.en.avs                   Modele de script AviSynth",
                "  UserGuide.txt                         Guide texte (source)",
                "",
                "  Assets/",
                "    Ico.ico                             Icone de l'application",
                "    Logo.png                            Logo",
                "",
                "  mpv/",
                "    libmpv-2.dll                        Lecteur video (libmpv)",
                "",
                "  Users Guide/",
                "    AvyscanLab_Guide_en.pdf              Guide utilisateur (anglais)",
                "    AvyscanLab_Guide_fr.pdf              Guide utilisateur (francais)",
                "    AvyscanLab_Guide_de.pdf              Guide utilisateur (allemand)",
                "    AvyscanLab_Guide_es.pdf              Guide utilisateur (espagnol)",
                "",
                "  Plugins/",
                "    Avisynth/",
                "      AviSynth.dll                      Moteur AviSynth+ embarque",
                "      DevIL.dll                         Chargement d'images (dependance)",
                "      ImageSeq.dll                      Support des sequences d'images",
                "",
                "    Dual/L-Smash-Works/",
                "      LSMASHSource.dll                  Decodeur L-SMASH (MP4/MOV)",
                "      LSMASHSource_indexing.exe          Outil d'indexation",
                "",
                "    ffmpeg/",
                "      ffmpeg.exe                        Encodeur video",
                "      ffprobe.exe                       Analyse de fichiers video",
                "      avcodec-62.dll                    Codec FFmpeg",
                "      avdevice-62.dll                   Peripheriques FFmpeg",
                "      avfilter-11.dll                   Filtres FFmpeg",
                "      avformat-62.dll                   Formats FFmpeg",
                "      avutil-60.dll                     Utilitaires FFmpeg",
                "      swresample-6.dll                  Reechantillonnage audio",
                "      swscale-9.dll                     Mise a l'echelle video",
                "",
                "    FFMS2/",
                "      ffms2.dll                         Decodeur FFMS2",
                "",
                "    GamMac/",
                "      GamMac_x64.dll                    Correction colorimetrique GamMac",
                "",
                "    Masktools2/",
                "      masktools2.dll                    Operations sur les masques",
                "",
                "    MVTools2/",
                "      mvtools2.dll                      Estimation et compensation de mouvement",
                "      DePan.dll                         Stabilisation DePan",
                "      DePanEstimate.dll                 Estimation DePan",
                "      Documentation/                    Documentation HTML de MVTools2",
                "",
                "    RemoveDirt/",
                "      RemoveDirt.dll                    Suppression des poussieres",
                "",
                "    RgTools/",
                "      RgTools.dll                       Outils de suppression de grain",
                "",
                "    Scripts/",
                "      FFMS2.avsi                        Script d'import FFMS2",
                "      RemoveDirt.avsi                   Script d'import RemoveDirt",
            ]),
        ],
        "footer": "Support : utilisez le formulaire Feedback integre dans l'application.",
    },

    "en": {
        "title": "C L E A N S C A N",
        "subtitle": "User Guide",
        "company": "ScanFilm SNC",
        "website": "www.scanfilm.ch",
        "version": "Trial version - Beta 5.0",
        "toc_title": "TABLE OF CONTENTS",
        "sections": [
            ("1. Introduction", [
                "ScanRestore is a restoration tool for digitized film (8 mm, Super 8, 9.5 mm, 16 mm).",
                "It allows you to:",
                "",
                "  - Reduce film grain",
                "  - Remove dust and scratches",
                "  - Correct brightness, contrast and colours",
                "  - Crop the image",
                "  - Enhance sharpness",
                "",
                "The software generates an optimized AviSynth+ script and provides real-time preview",
                "via an integrated video player (libmpv). Final encoding is handled by FFmpeg.",
            ]),
            ("2. Prerequisites and installation", [
                "System requirements:",
                "  - Windows 10 or 11 (64-bit)",
                "  - 4 GB RAM minimum (8 GB recommended)",
                "  - Sufficient disk space for source files and renders",
                "",
                "Components:",
                "  - AviSynth+ 64-bit must be installed. If missing, ScanRestore detects it at startup",
                "    and offers a download link. A bundled version is used as fallback.",
                "  - FFmpeg is included (Plugins/ffmpeg/ folder).",
                "  - The mpv player is included (mpv/ folder).",
                "",
                "No additional installation required. Extract the archive and run ScanRestore.exe.",
            ]),
            ("3. General interface", [
                "The interface is organized in three areas:",
                "",
                "TOP AREA",
                "  Menu bar: Infos, Preset, Settings, Feedback, Language, About.",
                "  Source bar: source file selection fields, image mode, FPS.",
                "  Clip tabs: each loaded clip appears as a tab.",
                "  Transport bar: playback controls, progress bar, Record button.",
                "",
                "CENTER AREA",
                "  mpv video player: displays the AviSynth script preview in real time.",
                "",
                "BOTTOM AREA",
                "  Filter panel: split into two columns separated by a resizable splitter.",
            ]),
            ("4. Source selection", [
                "Video file:",
                "  Drag-and-drop a video file onto the player area, or click the source field.",
                "  Supported formats: .avi .mp4 .mov .mkv .wmv .m4v .mpeg .mpg .webm",
                "",
                "Image sequence:",
                "  Enable image mode, then enter the folder path in the img field.",
                "  Supported formats: .tif .tiff .jpg .jpeg .png .bmp",
                "",
                "Frame rate (FPS):",
                "  16 fps (8 mm), 18 fps (Super 8), 24 fps (16 mm).",
                "",
                "Multi-clip:",
                "  You can load multiple files. Each clip has its own filter settings.",
            ]),
            ("5. Video player and navigation", [
                "The integrated player displays the AviSynth script result in real time.",
                "",
                "Keyboard shortcuts:",
                "  Space            Play / Pause",
                "  Left arrow       Previous frame",
                "  Right arrow      Next frame",
                "  Ctrl + Left      Go to beginning",
                "  Ctrl + Right     Go to end",
                "",
                "Transport bar:",
                "  |<  Start     <<  Previous     >  Play     >>  Next     >|  End",
                "  1x  Speed (0.25x, 0.5x, 1x)     1/2  Half-resolution",
            ]),
            ("6. Filter panel", [
                "The bottom panel is split into two columns:",
                "  Left column: activation buttons (ON/OFF)",
                "  Right column: detailed parameters",
                "",
                "Available filters:",
                "  - Crop: cropping (removes pixels from edges)",
                "  - Degrain: temporal grain reduction (MVTools2)",
                "  - Denoise: dust and scratch removal",
                "  - Luma: brightness, contrast, saturation, hue, gamma adjustment",
                "  - GamMac: automatic colour correction",
                "  - Sharpen: sharpness enhancement",
                "",
                "Hover over each parameter to display a tooltip.",
            ]),
            ("7. Presets", [
                "The Preset menu allows you to save and restore your complete filter configurations.",
                "",
                "  Save: stores current settings under a name",
                "  Load: applies an existing preset",
                "  Delete: removes a preset",
                "",
                "Source, film, img, start, end and crop fields are NOT included in presets.",
                "Location: %AppData%\\AvyscanLab\\presets.json",
            ]),
            ("8. Custom Filters", [
                "ScanRestore lets you create your own AviSynth filters and integrate them into the",
                "restoration pipeline. Custom filters appear in the CUSTOM section of the filter",
                "panel (left column).",
                "",
                "CREATING A CUSTOM FILTER",
                "",
                "  1. Click the \"+\" button next to the CUSTOM title in the filter panel.",
                "     The custom filter form opens.",
                "",
                "  2. Enter the filter name and position in the pipeline:",
                "     - BeforePipeline: before all filters",
                "     - AfterGamMac: after colour correction",
                "     - AfterDenoise: after dust removal",
                "     - AfterDegrain: after grain reduction",
                "     - AfterLuma: after brightness levels",
                "     - AfterSharpen: after sharpening (end of pipeline)",
                "",
                "  3. If your filter requires an external AviSynth plugin (.dll), click",
                "     \"+ Add DLL...\" to add it. DLLs are loaded via TryLoadPlugin() and",
                "     duplicates are automatically removed.",
                "",
                "  4. Write the AviSynth code in the editor. Use \"c\" as the clip variable:",
                "         c = MyFilter(c, strength={sigma})",
                "     Words in braces {name} are automatically detected as parameters.",
                "",
                "  5. For each detected parameter, configure the control type:",
                "     - slider: slider with Min, Max, Step and Default",
                "     - combo: drop-down list with comma-separated values",
                "     - checkbox: checkbox with On/Off values",
                "     - text: free text field",
                "",
                "  6. Use the \"Preview\" button to test the filter in real time without leaving",
                "     the form.",
                "",
                "  7. Click \"Save\" to save.",
                "",
                "USING A CUSTOM FILTER",
                "",
                "  The filter appears in the CUSTOM section with an ON/OFF button. Click it to",
                "  activate. The arrow button (>) opens the parameter panel. The pencil button",
                "  opens the edit form.",
                "",
                "EXPORT / IMPORT A FILTER",
                "",
                "  Export: in the edit form, click \"Export\". The filter is saved as a .json file",
                "  that you can share with other users.",
                "",
                "  Import: in the filter panel, click the down-arrow button next to \"+\" in the",
                "  CUSTOM section. Select an exported .json file. Imported filters receive a new",
                "  identifier to avoid duplicates.",
                "",
                "  Note: DLL paths are absolute. If the filter uses an external plugin, make sure",
                "  the DLL is present on the target machine.",
                "",
                "DELETE A FILTER",
                "",
                "  Open the edit form (pencil button) and click \"Delete\".",
                "",
                "Location: %AppData%\\AvyscanLab\\custom_filters.json",
            ]),
            ("9. Encoding and rendering", [
                "Click the REC button in the transport bar to open the encoding panel.",
                "",
                "  Step 1: Check the clips to encode in the list.",
                "  Step 2: Select the destination folder.",
                "  Step 3: Choose the encoder (x264, x265, FFV1, UT Video, ProRes, TIFF, PNG).",
                "  Step 4: Select the container (MKV, MP4, AVI, MOV).",
                "  Step 5: Adjust parameters (CRF/Bitrate, Chroma, Resolution).",
                "",
                "Encoding presets: save your frequent combinations.",
                "Location: %AppData%\\AvyscanLab\\encoding_presets.json",
                "",
                "\"Shutdown after completion\" option available for long encodes.",
            ]),
            ("10. Application settings", [
                "Settings menu:",
                "  Threads: number of AviSynth threads",
                "  Source loader: Auto, FFMS2, L-SMASH, LWLibav",
                "  Reset settings: resets all settings to defaults",
                "",
                "Language menu: Francais, English, Deutsch, Espanol.",
            ]),
            ("11. Script preview", [
                "Menu Infos > Script preview opens a window showing the full content of the",
                "ScriptUser.avs file generated by ScanRestore.",
                "The \"Reload\" button re-reads the file from disk.",
            ]),
            ("12. Feedback", [
                "The Feedback menu opens a built-in contact form allowing you to send:",
                "  - A bug report",
                "  - A feature request",
                "  - General feedback with rating",
            ]),
            ("13. Recommended workflow", [
                "  1. Open your source (drag-and-drop or source field).",
                "  2. Navigate to a representative frame.",
                "  3. Enable filters one by one:",
                "     a) Crop - Remove black borders",
                "     b) Degrain - Start with \"standard\" preset, then adjust thSAD",
                "     c) Denoise - Remove dust",
                "     d) Luma - Adjust brightness and contrast",
                "     e) GamMac - Correct colour drift",
                "     f) Sharpen - Enhance sharpness last",
                "     g) Custom - Add your custom filters if needed",
                "  4. Save your configuration as a preset.",
                "  5. Open the Record panel and start encoding.",
            ]),
            ("14. Tips and shortcuts", [
                "  - Mouse wheel on numeric fields adjusts the value by step.",
                "  - Half-resolution mode speeds up preview.",
                "  - All parameters are saved automatically.",
                "  - Window position and size are remembered.",
                "  - Tooltips (hover) show ranges and tips.",
                "  - Drag-and-drop multiple files to create one clip per file.",
                "  - Custom filters can be shared via JSON export/import.",
            ]),
            ("15. Files and locations", [
                "  ScriptUser.avs              Application folder",
                "  ScriptMaster.xx.avs         Application folder",
                "  ScriptRender.avs            Application folder",
                "  presets.json                %AppData%\\AvyscanLab",
                "  encoding_presets.json       %AppData%\\AvyscanLab",
                "  custom_filters.json         %AppData%\\AvyscanLab",
                "  window_settings.json        %AppData%\\AvyscanLab",
                "  session.json                %AppData%\\AvyscanLab",
                "  Plugins/                    Application folder",
                "  mpv/                        Application folder",
            ]),
            ("16. Application contents", [
                "File tree distributed with ScanRestore:",
                "",
                "  AvyscanLab.exe                         Main executable",
                "  ScriptMaster.en.avs                   AviSynth script template",
                "  UserGuide.txt                         Text guide (source)",
                "",
                "  Assets/",
                "    Ico.ico                             Application icon",
                "    Logo.png                            Logo",
                "",
                "  mpv/",
                "    libmpv-2.dll                        Video player (libmpv)",
                "",
                "  Users Guide/",
                "    AvyscanLab_Guide_en.pdf              User guide (English)",
                "    AvyscanLab_Guide_fr.pdf              User guide (French)",
                "    AvyscanLab_Guide_de.pdf              User guide (German)",
                "    AvyscanLab_Guide_es.pdf              User guide (Spanish)",
                "",
                "  Plugins/",
                "    Avisynth/",
                "      AviSynth.dll                      Bundled AviSynth+ engine",
                "      DevIL.dll                         Image loading (dependency)",
                "      ImageSeq.dll                      Image sequence support",
                "",
                "    Dual/L-Smash-Works/",
                "      LSMASHSource.dll                  L-SMASH decoder (MP4/MOV)",
                "      LSMASHSource_indexing.exe          Indexing tool",
                "",
                "    ffmpeg/",
                "      ffmpeg.exe                        Video encoder",
                "      ffprobe.exe                       Video file analyser",
                "      avcodec-62.dll                    FFmpeg codec library",
                "      avdevice-62.dll                   FFmpeg device library",
                "      avfilter-11.dll                   FFmpeg filter library",
                "      avformat-62.dll                   FFmpeg format library",
                "      avutil-60.dll                     FFmpeg utility library",
                "      swresample-6.dll                  Audio resampling",
                "      swscale-9.dll                     Video scaling",
                "",
                "    FFMS2/",
                "      ffms2.dll                         FFMS2 decoder",
                "",
                "    GamMac/",
                "      GamMac_x64.dll                    GamMac colour correction",
                "",
                "    Masktools2/",
                "      masktools2.dll                    Mask operations",
                "",
                "    MVTools2/",
                "      mvtools2.dll                      Motion estimation and compensation",
                "      DePan.dll                         DePan stabilisation",
                "      DePanEstimate.dll                 DePan estimation",
                "      Documentation/                    MVTools2 HTML documentation",
                "",
                "    RemoveDirt/",
                "      RemoveDirt.dll                    Dust removal",
                "",
                "    RgTools/",
                "      RgTools.dll                       Grain removal tools",
                "",
                "    Scripts/",
                "      FFMS2.avsi                        FFMS2 import script",
                "      RemoveDirt.avsi                   RemoveDirt import script",
            ]),
        ],
        "footer": "Support: use the built-in Feedback form in the application.",
    },

    "de": {
        "title": "C L E A N S C A N",
        "subtitle": "Benutzerhandbuch",
        "company": "ScanFilm SNC",
        "website": "www.scanfilm.ch",
        "version": "Testversion - Beta 5.0",
        "toc_title": "INHALTSVERZEICHNIS",
        "sections": [
            ("1. Vorstellung", [
                "ScanRestore ist ein Restaurierungstool fuer digitalisierte Filme (8 mm, Super 8,",
                "9,5 mm, 16 mm). Es ermoeglicht:",
                "",
                "  - Filmkorn reduzieren",
                "  - Staub und Kratzer entfernen",
                "  - Helligkeit, Kontrast und Farben korrigieren",
                "  - Bild zuschneiden",
                "  - Schaerfe verbessern",
                "",
                "Die Software generiert ein optimiertes AviSynth+-Skript und bietet eine Echtzeit-",
                "Vorschau ueber einen integrierten Videoplayer (libmpv). FFmpeg kodiert die Ausgabe.",
            ]),
            ("2. Voraussetzungen und Installation", [
                "Systemanforderungen:",
                "  - Windows 10 oder 11 (64-Bit)",
                "  - Mindestens 4 GB RAM (8 GB empfohlen)",
                "  - Ausreichend Speicherplatz fuer Quell- und Ausgabedateien",
                "",
                "Komponenten:",
                "  - AviSynth+ 64-Bit muss installiert sein. Falls nicht, erkennt ScanRestore dies",
                "    beim Start und bietet einen Download-Link an.",
                "  - FFmpeg ist enthalten (Plugins/ffmpeg/).",
                "  - Der mpv-Player ist enthalten (mpv/).",
                "",
                "Keine zusaetzliche Installation erforderlich. Archiv entpacken und ScanRestore.exe starten.",
            ]),
            ("3. Allgemeine Oberflaeche", [
                "Die Oberflaeche ist in drei Bereiche unterteilt:",
                "",
                "OBERER BEREICH",
                "  Menueleiste: Infos, Preset, Einstellungen, Feedback, Sprache, Ueber.",
                "  Quellleiste: Quelldateiauswahl, Bildmodus, FPS.",
                "  Clip-Tabs: jeder geladene Clip erscheint als Registerkarte.",
                "  Transportleiste: Wiedergabesteuerung, Fortschrittsbalken, Record-Taste.",
                "",
                "MITTLERER BEREICH",
                "  mpv-Videoplayer: zeigt die AviSynth-Skript-Vorschau in Echtzeit.",
                "",
                "UNTERER BEREICH",
                "  Filterpanel: in zwei Spalten mit anpassbarem Trenner unterteilt.",
            ]),
            ("4. Quellauswahl", [
                "Videodatei:",
                "  Ziehen Sie eine Videodatei in den Playerbereich oder klicken Sie auf das Quellfeld.",
                "  Unterstuetzte Formate: .avi .mp4 .mov .mkv .wmv .m4v .mpeg .mpg .webm",
                "",
                "Bildsequenz:",
                "  Aktivieren Sie den Bildmodus und geben Sie den Ordnerpfad im img-Feld ein.",
                "  Unterstuetzte Formate: .tif .tiff .jpg .jpeg .png .bmp",
                "",
                "Bildrate (FPS):",
                "  16 fps (8 mm), 18 fps (Super 8), 24 fps (16 mm).",
                "",
                "Multi-Clip:",
                "  Mehrere Dateien laden moeglich. Jeder Clip hat eigene Filtereinstellungen.",
            ]),
            ("5. Videoplayer und Navigation", [
                "Der integrierte Player zeigt das AviSynth-Ergebnis in Echtzeit.",
                "",
                "Tastaturkuerzel:",
                "  Leertaste        Wiedergabe / Pause",
                "  Pfeil links      Vorheriges Bild",
                "  Pfeil rechts     Naechstes Bild",
                "  Strg + Links     Zum Anfang",
                "  Strg + Rechts    Zum Ende",
            ]),
            ("6. Filterpanel", [
                "Das untere Panel ist in zwei Spalten unterteilt:",
                "  Linke Spalte: Aktivierungstasten (EIN/AUS)",
                "  Rechte Spalte: detaillierte Parameter",
                "",
                "Verfuegbare Filter:",
                "  - Crop: Zuschnitt",
                "  - Degrain: temporale Kornreduzierung (MVTools2)",
                "  - Denoise: Staub- und Kratzerentfernung",
                "  - Luma: Helligkeit, Kontrast, Saettigung, Farbton, Gamma",
                "  - GamMac: automatische Farbkorrektur",
                "  - Sharpen: Schaerfeverbesserung",
            ]),
            ("7. Presets", [
                "Das Preset-Menue ermoeglicht das Speichern und Laden Ihrer Filterkonfigurationen.",
                "",
                "  Speichern: aktuelle Einstellungen unter einem Namen speichern",
                "  Laden: ein vorhandenes Preset anwenden",
                "  Loeschen: ein Preset entfernen",
                "",
                "Speicherort: %AppData%\\AvyscanLab\\presets.json",
            ]),
            ("8. Benutzerdefinierte Filter (Custom)", [
                "ScanRestore ermoeglicht es, eigene AviSynth-Filter zu erstellen und in die",
                "Restaurierungspipeline zu integrieren. Benutzerdefinierte Filter erscheinen im",
                "Abschnitt CUSTOM des Filterpanels (linke Spalte).",
                "",
                "BENUTZERDEFINIERTEN FILTER ERSTELLEN",
                "",
                "  1. Klicken Sie auf \"+\" neben dem CUSTOM-Titel im Filterpanel.",
                "     Das Formular fuer benutzerdefinierte Filter oeffnet sich.",
                "",
                "  2. Geben Sie den Filternamen und die Position in der Pipeline ein:",
                "     - BeforePipeline: vor allen Filtern",
                "     - AfterGamMac: nach der Farbkorrektur",
                "     - AfterDenoise: nach der Staubentfernung",
                "     - AfterDegrain: nach der Kornreduzierung",
                "     - AfterLuma: nach den Helligkeitsstufen",
                "     - AfterSharpen: nach der Schaerfe (Ende der Pipeline)",
                "",
                "  3. Falls Ihr Filter ein externes AviSynth-Plugin (.dll) benoetigt, klicken Sie",
                "     auf \"+ DLL hinzufuegen...\". DLLs werden ueber TryLoadPlugin() geladen,",
                "     Duplikate werden automatisch entfernt.",
                "",
                "  4. Schreiben Sie den AviSynth-Code im Editor. Verwenden Sie \"c\" als Clip-Variable:",
                "         c = MeinFilter(c, staerke={sigma})",
                "     Woerter in geschweiften Klammern {Name} werden als Parameter erkannt.",
                "",
                "  5. Fuer jeden erkannten Parameter konfigurieren Sie den Steuerungstyp:",
                "     - slider: Schieberegler mit Min, Max, Schritt und Standard",
                "     - combo: Auswahlliste mit kommaseparierten Werten",
                "     - checkbox: Kontrollkaestchen mit Ein/Aus-Werten",
                "     - text: freies Textfeld",
                "",
                "  6. Verwenden Sie \"Vorschau\" zum Testen in Echtzeit.",
                "",
                "  7. Klicken Sie auf \"Speichern\".",
                "",
                "FILTER VERWENDEN",
                "",
                "  Der Filter erscheint im CUSTOM-Bereich mit EIN/AUS-Taste. Der Pfeil-Button (>)",
                "  oeffnet das Parameterpanel. Der Stift-Button oeffnet das Bearbeitungsformular.",
                "",
                "EXPORTIEREN / IMPORTIEREN",
                "",
                "  Exportieren: Im Bearbeitungsformular auf \"Exportieren\" klicken. Der Filter wird",
                "  als .json-Datei gespeichert, die Sie teilen koennen.",
                "",
                "  Importieren: Im Filterpanel auf den Abwaertspfeil neben \"+\" im CUSTOM-Bereich",
                "  klicken. Eine exportierte .json-Datei auswaehlen. Importierte Filter erhalten",
                "  eine neue Kennung.",
                "",
                "  Hinweis: DLL-Pfade sind absolut. Stellen Sie sicher, dass die DLL auf dem",
                "  Zielrechner vorhanden ist.",
                "",
                "FILTER LOESCHEN",
                "",
                "  Bearbeitungsformular oeffnen (Stift-Button) und \"Loeschen\" klicken.",
                "",
                "Speicherort: %AppData%\\AvyscanLab\\custom_filters.json",
            ]),
            ("9. Kodierung und Rendering", [
                "Klicken Sie auf REC in der Transportleiste, um das Kodierungspanel zu oeffnen.",
                "",
                "  Schritt 1: Clips in der Liste ankreuzen.",
                "  Schritt 2: Zielordner auswaehlen.",
                "  Schritt 3: Encoder waehlen (x264, x265, FFV1, UT Video, ProRes, TIFF, PNG).",
                "  Schritt 4: Container waehlen (MKV, MP4, AVI, MOV).",
                "  Schritt 5: Parameter anpassen (CRF/Bitrate, Chroma, Aufloesung).",
                "",
                "Kodierungspresets: Haeufige Kombinationen speichern.",
                "Speicherort: %AppData%\\AvyscanLab\\encoding_presets.json",
            ]),
            ("10. Anwendungseinstellungen", [
                "Einstellungsmenue:",
                "  Threads: Anzahl der AviSynth-Threads",
                "  Quellenlader: Auto, FFMS2, L-SMASH, LWLibav",
                "  Zuruecksetzen: alle Einstellungen auf Standard zuruecksetzen",
                "",
                "Sprachmenue: Francais, English, Deutsch, Espanol.",
            ]),
            ("11. Skript-Vorschau", [
                "Menue Infos > Skript-Vorschau oeffnet ein Fenster mit dem vollstaendigen Inhalt",
                "der von ScanRestore generierten ScriptUser.avs-Datei.",
            ]),
            ("12. Feedback", [
                "Das Feedback-Menue oeffnet ein integriertes Kontaktformular:",
                "  - Fehlerbericht",
                "  - Funktionswunsch",
                "  - Allgemeines Feedback mit Bewertung",
            ]),
            ("13. Empfohlener Workflow", [
                "  1. Quelle oeffnen (Drag-and-Drop oder Quellfeld).",
                "  2. Zu einem repraesentativen Bild navigieren.",
                "  3. Filter nacheinander aktivieren:",
                "     a) Crop - Schwarze Raender entfernen",
                "     b) Degrain - Preset \"Standard\", dann thSAD anpassen",
                "     c) Denoise - Staub entfernen",
                "     d) Luma - Helligkeit und Kontrast anpassen",
                "     e) GamMac - Farbabweichungen korrigieren",
                "     f) Sharpen - Schaerfe zuletzt verbessern",
                "     g) Custom - Eigene Filter bei Bedarf hinzufuegen",
                "  4. Konfiguration als Preset speichern.",
                "  5. Record-Panel oeffnen und Kodierung starten.",
            ]),
            ("14. Tipps und Tastenkuerzel", [
                "  - Mausrad auf Zahlenfeldern aendert den Wert schrittweise.",
                "  - Halbaufloesung beschleunigt die Vorschau.",
                "  - Alle Parameter werden automatisch gespeichert.",
                "  - Fensterposition und -groesse werden gespeichert.",
                "  - Tooltips zeigen Bereiche und Tipps.",
                "  - Benutzerdefinierte Filter koennen per JSON-Export/Import geteilt werden.",
            ]),
            ("15. Dateien und Speicherorte", [
                "  ScriptUser.avs              Anwendungsordner",
                "  ScriptMaster.xx.avs         Anwendungsordner",
                "  ScriptRender.avs            Anwendungsordner",
                "  presets.json                %AppData%\\AvyscanLab",
                "  encoding_presets.json       %AppData%\\AvyscanLab",
                "  custom_filters.json         %AppData%\\AvyscanLab",
                "  window_settings.json        %AppData%\\AvyscanLab",
                "  session.json                %AppData%\\AvyscanLab",
                "  Plugins/                    Anwendungsordner",
                "  mpv/                        Anwendungsordner",
            ]),
            ("16. Anwendungsinhalt", [
                "Dateibaum, der mit ScanRestore ausgeliefert wird:",
                "",
                "  AvyscanLab.exe                         Hauptprogramm",
                "  ScriptMaster.en.avs                   AviSynth-Skriptvorlage",
                "  UserGuide.txt                         Textanleitung (Quelle)",
                "",
                "  Assets/",
                "    Ico.ico                             Anwendungssymbol",
                "    Logo.png                            Logo",
                "",
                "  mpv/",
                "    libmpv-2.dll                        Videoplayer (libmpv)",
                "",
                "  Users Guide/",
                "    AvyscanLab_Guide_en.pdf              Benutzerhandbuch (Englisch)",
                "    AvyscanLab_Guide_fr.pdf              Benutzerhandbuch (Franzoesisch)",
                "    AvyscanLab_Guide_de.pdf              Benutzerhandbuch (Deutsch)",
                "    AvyscanLab_Guide_es.pdf              Benutzerhandbuch (Spanisch)",
                "",
                "  Plugins/",
                "    Avisynth/",
                "      AviSynth.dll                      Eingebettete AviSynth+-Engine",
                "      DevIL.dll                         Bildladen (Abhaengigkeit)",
                "      ImageSeq.dll                      Bildsequenz-Unterstuetzung",
                "",
                "    Dual/L-Smash-Works/",
                "      LSMASHSource.dll                  L-SMASH-Decoder (MP4/MOV)",
                "      LSMASHSource_indexing.exe          Indexierungswerkzeug",
                "",
                "    ffmpeg/",
                "      ffmpeg.exe                        Video-Encoder",
                "      ffprobe.exe                       Videodatei-Analysator",
                "      avcodec-62.dll                    FFmpeg-Codec-Bibliothek",
                "      avdevice-62.dll                   FFmpeg-Geraete-Bibliothek",
                "      avfilter-11.dll                   FFmpeg-Filter-Bibliothek",
                "      avformat-62.dll                   FFmpeg-Format-Bibliothek",
                "      avutil-60.dll                     FFmpeg-Hilfsbibliothek",
                "      swresample-6.dll                  Audio-Resampling",
                "      swscale-9.dll                     Video-Skalierung",
                "",
                "    FFMS2/",
                "      ffms2.dll                         FFMS2-Decoder",
                "",
                "    GamMac/",
                "      GamMac_x64.dll                    GamMac-Farbkorrektur",
                "",
                "    Masktools2/",
                "      masktools2.dll                    Maskenoperationen",
                "",
                "    MVTools2/",
                "      mvtools2.dll                      Bewegungsschaetzung und -kompensation",
                "      DePan.dll                         DePan-Stabilisierung",
                "      DePanEstimate.dll                 DePan-Schaetzung",
                "      Documentation/                    MVTools2-HTML-Dokumentation",
                "",
                "    RemoveDirt/",
                "      RemoveDirt.dll                    Staubentfernung",
                "",
                "    RgTools/",
                "      RgTools.dll                       Kornentfernungswerkzeuge",
                "",
                "    Scripts/",
                "      FFMS2.avsi                        FFMS2-Importskript",
                "      RemoveDirt.avsi                   RemoveDirt-Importskript",
            ]),
        ],
        "footer": "Support: Verwenden Sie das integrierte Feedback-Formular in der Anwendung.",
    },

    "es": {
        "title": "C L E A N S C A N",
        "subtitle": "Guia del usuario",
        "company": "ScanFilm SNC",
        "website": "www.scanfilm.ch",
        "version": "Version de prueba - Beta 5.0",
        "toc_title": "INDICE",
        "sections": [
            ("1. Presentacion", [
                "ScanRestore es una herramienta de restauracion para peliculas digitalizadas (8 mm,",
                "Super 8, 9,5 mm, 16 mm). Permite:",
                "",
                "  - Reducir el grano de pelicula",
                "  - Eliminar polvo y rayaduras",
                "  - Corregir brillo, contraste y colores",
                "  - Recortar la imagen",
                "  - Mejorar la nitidez",
                "",
                "El software genera un script AviSynth+ optimizado y ofrece una vista previa en",
                "tiempo real mediante un reproductor de video integrado (libmpv). FFmpeg codifica.",
            ]),
            ("2. Requisitos e instalacion", [
                "Requisitos del sistema:",
                "  - Windows 10 u 11 (64 bits)",
                "  - 4 GB de RAM minimo (8 GB recomendado)",
                "  - Espacio en disco suficiente para archivos fuente y renders",
                "",
                "Componentes:",
                "  - AviSynth+ 64 bits debe estar instalado. Si falta, ScanRestore lo detecta al",
                "    inicio y ofrece un enlace de descarga.",
                "  - FFmpeg esta incluido (carpeta Plugins/ffmpeg/).",
                "  - El reproductor mpv esta incluido (carpeta mpv/).",
                "",
                "No se requiere instalacion adicional. Extraiga el archivo y ejecute ScanRestore.exe.",
            ]),
            ("3. Interfaz general", [
                "La interfaz esta organizada en tres areas:",
                "",
                "AREA SUPERIOR",
                "  Barra de menus: Infos, Preset, Ajustes, Comentarios, Idioma, Acerca de.",
                "  Barra de fuente: campos de seleccion de archivo, modo imagen, FPS.",
                "  Pestanas de clips: cada clip cargado aparece como pestana.",
                "  Barra de transporte: controles de reproduccion, barra de progreso, boton Grabar.",
                "",
                "AREA CENTRAL",
                "  Reproductor de video mpv: muestra la vista previa del script AviSynth.",
                "",
                "AREA INFERIOR",
                "  Panel de filtros: dividido en dos columnas con separador ajustable.",
            ]),
            ("4. Seleccion de fuente", [
                "Archivo de video:",
                "  Arrastre un archivo de video al reproductor o haga clic en el campo fuente.",
                "  Formatos soportados: .avi .mp4 .mov .mkv .wmv .m4v .mpeg .mpg .webm",
                "",
                "Secuencia de imagenes:",
                "  Active el modo imagen e introduzca la ruta de la carpeta en el campo img.",
                "  Formatos soportados: .tif .tiff .jpg .jpeg .png .bmp",
                "",
                "Velocidad de fotogramas (FPS):",
                "  16 fps (8 mm), 18 fps (Super 8), 24 fps (16 mm).",
                "",
                "Multi-clip:",
                "  Puede cargar varios archivos. Cada clip tiene sus propios ajustes de filtros.",
            ]),
            ("5. Reproductor de video y navegacion", [
                "El reproductor integrado muestra el resultado del script AviSynth en tiempo real.",
                "",
                "Atajos de teclado:",
                "  Espacio           Reproducir / Pausa",
                "  Flecha izquierda  Fotograma anterior",
                "  Flecha derecha    Fotograma siguiente",
                "  Ctrl + Izquierda  Ir al inicio",
                "  Ctrl + Derecha    Ir al final",
            ]),
            ("6. Panel de filtros", [
                "El panel inferior se divide en dos columnas:",
                "  Columna izquierda: botones de activacion (ON/OFF)",
                "  Columna derecha: parametros detallados",
                "",
                "Filtros disponibles:",
                "  - Crop: recorte de imagen",
                "  - Degrain: reduccion temporal de grano (MVTools2)",
                "  - Denoise: eliminacion de polvo y rayaduras",
                "  - Luma: brillo, contraste, saturacion, tono, gamma",
                "  - GamMac: correccion automatica de color",
                "  - Sharpen: mejora de nitidez",
            ]),
            ("7. Presets", [
                "El menu Preset permite guardar y restaurar sus configuraciones de filtros.",
                "",
                "  Guardar: almacena los ajustes actuales con un nombre",
                "  Cargar: aplica un preset existente",
                "  Eliminar: borra un preset",
                "",
                "Ubicacion: %AppData%\\AvyscanLab\\presets.json",
            ]),
            ("8. Filtros personalizados (Custom)", [
                "ScanRestore permite crear sus propios filtros AviSynth e integrarlos en el pipeline",
                "de restauracion. Los filtros personalizados aparecen en la seccion CUSTOM del",
                "panel de filtros (columna izquierda).",
                "",
                "CREAR UN FILTRO PERSONALIZADO",
                "",
                "  1. Haga clic en \"+\" junto al titulo CUSTOM en el panel de filtros.",
                "     Se abre el formulario de filtro personalizado.",
                "",
                "  2. Introduzca el nombre del filtro y la posicion en el pipeline:",
                "     - BeforePipeline: antes de todos los filtros",
                "     - AfterGamMac: despues de la correccion de color",
                "     - AfterDenoise: despues de la eliminacion de polvo",
                "     - AfterDegrain: despues de la reduccion de grano",
                "     - AfterLuma: despues de los niveles de brillo",
                "     - AfterSharpen: despues de la nitidez (final del pipeline)",
                "",
                "  3. Si su filtro necesita un plugin AviSynth externo (.dll), haga clic en",
                "     \"+ Anadir DLL...\". Las DLLs se cargan mediante TryLoadPlugin() y los",
                "     duplicados se eliminan automaticamente.",
                "",
                "  4. Escriba el codigo AviSynth en el editor. Use \"c\" como variable de clip:",
                "         c = MiFiltro(c, fuerza={sigma})",
                "     Las palabras entre llaves {nombre} se detectan como parametros.",
                "",
                "  5. Para cada parametro detectado, configure el tipo de control:",
                "     - slider: control deslizante con Min, Max, Paso y Predeterminado",
                "     - combo: lista desplegable con valores separados por coma",
                "     - checkbox: casilla de verificacion con valores On/Off",
                "     - text: campo de texto libre",
                "",
                "  6. Use \"Vista previa\" para probar el filtro en tiempo real.",
                "",
                "  7. Haga clic en \"Guardar\".",
                "",
                "USAR UN FILTRO PERSONALIZADO",
                "",
                "  El filtro aparece en la seccion CUSTOM con un boton ON/OFF. El boton flecha (>)",
                "  abre el panel de parametros. El boton lapiz abre el formulario de edicion.",
                "",
                "EXPORTAR / IMPORTAR UN FILTRO",
                "",
                "  Exportar: en el formulario de edicion, haga clic en \"Exportar\". El filtro se",
                "  guarda como archivo .json que puede compartir.",
                "",
                "  Importar: en el panel de filtros, haga clic en la flecha hacia abajo junto a",
                "  \"+\" en la seccion CUSTOM. Seleccione un archivo .json exportado. Los filtros",
                "  importados reciben un nuevo identificador.",
                "",
                "  Nota: las rutas DLL son absolutas. Asegurese de que la DLL este presente en",
                "  la maquina de destino.",
                "",
                "ELIMINAR UN FILTRO",
                "",
                "  Abra el formulario de edicion (boton lapiz) y haga clic en \"Eliminar\".",
                "",
                "Ubicacion: %AppData%\\AvyscanLab\\custom_filters.json",
            ]),
            ("9. Codificacion y renderizado", [
                "Haga clic en REC en la barra de transporte para abrir el panel de codificacion.",
                "",
                "  Paso 1: Marque los clips a codificar en la lista.",
                "  Paso 2: Seleccione la carpeta de destino.",
                "  Paso 3: Elija el codificador (x264, x265, FFV1, UT Video, ProRes, TIFF, PNG).",
                "  Paso 4: Seleccione el contenedor (MKV, MP4, AVI, MOV).",
                "  Paso 5: Ajuste los parametros (CRF/Bitrate, Chroma, Resolucion).",
                "",
                "Presets de codificacion: guarde sus combinaciones frecuentes.",
                "Ubicacion: %AppData%\\AvyscanLab\\encoding_presets.json",
            ]),
            ("10. Ajustes de la aplicacion", [
                "Menu Ajustes:",
                "  Threads: numero de threads de AviSynth",
                "  Cargador de fuente: Auto, FFMS2, L-SMASH, LWLibav",
                "  Restablecer: restablece todos los ajustes predeterminados",
                "",
                "Menu Idioma: Francais, English, Deutsch, Espanol.",
            ]),
            ("11. Vista previa del script", [
                "Menu Infos > Vista previa del script abre una ventana con el contenido completo",
                "del archivo ScriptUser.avs generado por ScanRestore.",
            ]),
            ("12. Comentarios (Feedback)", [
                "El menu Comentarios abre un formulario de contacto integrado:",
                "  - Reporte de error",
                "  - Solicitud de funcion",
                "  - Comentario general con calificacion",
            ]),
            ("13. Flujo de trabajo recomendado", [
                "  1. Abra su fuente (arrastrar y soltar o campo fuente).",
                "  2. Navegue hasta un fotograma representativo.",
                "  3. Active los filtros uno por uno:",
                "     a) Crop - Eliminar bordes negros",
                "     b) Degrain - Preset \"estandar\", luego ajustar thSAD",
                "     c) Denoise - Eliminar polvo",
                "     d) Luma - Ajustar brillo y contraste",
                "     e) GamMac - Corregir desviaciones de color",
                "     f) Sharpen - Mejorar nitidez al final",
                "     g) Custom - Anadir filtros personalizados si es necesario",
                "  4. Guardar la configuracion como preset.",
                "  5. Abrir el panel Record e iniciar la codificacion.",
            ]),
            ("14. Consejos y atajos", [
                "  - La rueda del raton en los campos numericos ajusta el valor por pasos.",
                "  - El modo media resolucion acelera la vista previa.",
                "  - Todos los parametros se guardan automaticamente.",
                "  - La posicion y tamano de la ventana se recuerdan.",
                "  - Los tooltips muestran rangos y consejos.",
                "  - Los filtros personalizados se pueden compartir via exportacion/importacion JSON.",
            ]),
            ("15. Archivos y ubicaciones", [
                "  ScriptUser.avs              Carpeta de la aplicacion",
                "  ScriptMaster.xx.avs         Carpeta de la aplicacion",
                "  ScriptRender.avs            Carpeta de la aplicacion",
                "  presets.json                %AppData%\\AvyscanLab",
                "  encoding_presets.json       %AppData%\\AvyscanLab",
                "  custom_filters.json         %AppData%\\AvyscanLab",
                "  window_settings.json        %AppData%\\AvyscanLab",
                "  session.json                %AppData%\\AvyscanLab",
                "  Plugins/                    Carpeta de la aplicacion",
                "  mpv/                        Carpeta de la aplicacion",
            ]),
            ("16. Contenido de la aplicacion", [
                "Arbol de archivos distribuidos con ScanRestore:",
                "",
                "  AvyscanLab.exe                         Ejecutable principal",
                "  ScriptMaster.en.avs                   Plantilla de script AviSynth",
                "  UserGuide.txt                         Guia de texto (fuente)",
                "",
                "  Assets/",
                "    Ico.ico                             Icono de la aplicacion",
                "    Logo.png                            Logo",
                "",
                "  mpv/",
                "    libmpv-2.dll                        Reproductor de video (libmpv)",
                "",
                "  Users Guide/",
                "    AvyscanLab_Guide_en.pdf              Guia del usuario (ingles)",
                "    AvyscanLab_Guide_fr.pdf              Guia del usuario (frances)",
                "    AvyscanLab_Guide_de.pdf              Guia del usuario (aleman)",
                "    AvyscanLab_Guide_es.pdf              Guia del usuario (espanol)",
                "",
                "  Plugins/",
                "    Avisynth/",
                "      AviSynth.dll                      Motor AviSynth+ integrado",
                "      DevIL.dll                         Carga de imagenes (dependencia)",
                "      ImageSeq.dll                      Soporte de secuencias de imagenes",
                "",
                "    Dual/L-Smash-Works/",
                "      LSMASHSource.dll                  Decodificador L-SMASH (MP4/MOV)",
                "      LSMASHSource_indexing.exe          Herramienta de indexacion",
                "",
                "    ffmpeg/",
                "      ffmpeg.exe                        Codificador de video",
                "      ffprobe.exe                       Analizador de archivos de video",
                "      avcodec-62.dll                    Biblioteca de codecs FFmpeg",
                "      avdevice-62.dll                   Biblioteca de dispositivos FFmpeg",
                "      avfilter-11.dll                   Biblioteca de filtros FFmpeg",
                "      avformat-62.dll                   Biblioteca de formatos FFmpeg",
                "      avutil-60.dll                     Biblioteca de utilidades FFmpeg",
                "      swresample-6.dll                  Remuestreo de audio",
                "      swscale-9.dll                     Escalado de video",
                "",
                "    FFMS2/",
                "      ffms2.dll                         Decodificador FFMS2",
                "",
                "    GamMac/",
                "      GamMac_x64.dll                    Correccion de color GamMac",
                "",
                "    Masktools2/",
                "      masktools2.dll                    Operaciones de mascaras",
                "",
                "    MVTools2/",
                "      mvtools2.dll                      Estimacion y compensacion de movimiento",
                "      DePan.dll                         Estabilizacion DePan",
                "      DePanEstimate.dll                 Estimacion DePan",
                "      Documentation/                    Documentacion HTML de MVTools2",
                "",
                "    RemoveDirt/",
                "      RemoveDirt.dll                    Eliminacion de polvo",
                "",
                "    RgTools/",
                "      RgTools.dll                       Herramientas de eliminacion de grano",
                "",
                "    Scripts/",
                "      FFMS2.avsi                        Script de importacion FFMS2",
                "      RemoveDirt.avsi                   Script de importacion RemoveDirt",
            ]),
        ],
        "footer": "Soporte: utilice el formulario de Comentarios integrado en la aplicacion.",
    },
}


class GuidePDF(FPDF):
    def __init__(self, guide_data):
        super().__init__()
        self.guide = guide_data
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        if self.page_no() > 1:
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(120, 120, 120)
            self.cell(0, 6, f"ScanRestore - {self.guide['subtitle']}", align="L")
            self.cell(0, 6, f"Beta 5.0", align="R", new_x="LMARGIN", new_y="NEXT")
            self.line(10, 14, 200, 14)
            self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, f"{self.guide['company']}  -  {self.guide['website']}", align="L")
        self.cell(0, 10, str(self.page_no()), align="R")


def generate_pdf(lang, guide_data):
    pdf = GuidePDF(guide_data)
    pdf.add_page()

    # ─── Cover page ───
    pdf.ln(40)
    pdf.set_font("Helvetica", "B", 28)
    pdf.set_text_color(30, 40, 60)
    pdf.cell(0, 14, guide_data["title"], align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)
    pdf.set_font("Helvetica", "", 16)
    pdf.set_text_color(60, 80, 120)
    pdf.cell(0, 10, guide_data["subtitle"], align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)
    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 8, guide_data["company"], align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, guide_data["website"], align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 11)
    pdf.set_text_color(180, 140, 40)
    pdf.cell(0, 8, guide_data["version"], align="C", new_x="LMARGIN", new_y="NEXT")

    # ─── Table of contents ───
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(30, 40, 60)
    pdf.cell(0, 10, guide_data["toc_title"], align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(40, 40, 40)
    for title, _ in guide_data["sections"]:
        pdf.cell(0, 7, title, new_x="LMARGIN", new_y="NEXT")

    # ─── Sections ───
    for title, lines in guide_data["sections"]:
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(30, 40, 60)
        pdf.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(4)

        pdf.set_font("Courier", "", 9)
        pdf.set_text_color(40, 40, 40)
        for line in lines:
            if line == "":
                pdf.ln(3)
            elif line.isupper() and len(line) > 4 and not line.startswith(" "):
                # Sub-heading
                pdf.ln(2)
                pdf.set_font("Helvetica", "B", 10)
                pdf.set_text_color(60, 80, 120)
                pdf.cell(0, 6, line, new_x="LMARGIN", new_y="NEXT")
                pdf.set_font("Courier", "", 9)
                pdf.set_text_color(40, 40, 40)
                pdf.ln(1)
            else:
                pdf.cell(0, 5, line, new_x="LMARGIN", new_y="NEXT")

    # ─── Footer page ───
    pdf.add_page()
    pdf.ln(40)
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(30, 40, 60)
    pdf.cell(0, 12, guide_data["title"], align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)
    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 8, guide_data["company"], align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, guide_data["website"], align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 10)
    pdf.cell(0, 8, guide_data["footer"], align="C", new_x="LMARGIN", new_y="NEXT")

    out_path = os.path.join(OUT_DIR, f"AvyscanLab_Guide_{lang}.pdf")
    pdf.output(out_path)
    print(f"  Generated: {out_path}")


if __name__ == "__main__":
    print("Generating ScanRestore User Guides...")
    for lang, data in GUIDES.items():
        generate_pdf(lang, data)
    print("Done!")
